doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            payment_type_enum: App\Modules\Payment\Entity\PaymentType

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Order:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Order/Entity'
                prefix: 'App\Modules\Order\Entity'
                alias: Order
            Payment:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Payment/Entity'
                prefix: 'App\Modules\Payment\Entity'
                alias: Payment

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
